server:
  port: 8021
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver